.android:
  image: mingc/android-build-box:1.20.0
  before_script:
    - gem update --system
    - gem install bundler:1.17.2
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - export BUNDLE_GEMFILE=$(pwd)/Gemfile
    - bundle install
    - fastlane install_plugins --verbose
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle/wrapper
      - .gradle/caches
.ios:
  before_script:
    - bundle install
    - fastlane install_plugins --verbose
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ./node_modules

stages:
  - deploy

variables:
  GIT_SSL_NO_VERIFY: "true"

deploy:android:beta:
  stage: deploy
  extends: .android
  script: 
    - npm ci
    - bundle exec fastlane android beta
  tags:
    - mobile
  when: manual

deploy:ios:beta:
  stage: deploy
  extends: .ios
  script:
    - npm ci
    - bundle exec fastlane ios beta
  tags:
    - mac-shell
  when: manual

deploy:ios:release:
  stage: deploy
  extends: .ios
  script:
    - npm ci
    - bundle exec fastlane ios release
  tags:
    - mac-shell
  only:
    - tags
  when: manual


