# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Appcenter"
  lane :beta do
    current_version = appcenter_fetch_version_number
    new_build_number = current_version["build_number"].to_i + 1

    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'release', project_dir: 'android/')

    appcenter_upload(
      app_name: ENV["APPCENTER_APP_NAME"],
      apk: ENV["RESULT_DEV_APK"]
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end
