export const LOAD_ALBUMS = 'LOAD_ALBUMS';
export const TOGGLE_ALBUM = 'TOGGLE_ALBUM';
export const OPEN_ALBUM = 'OPEN_ALBUM';
export const ALBUM_CHANGED = 'ALBUM_CHANGED';
export const UPDATE_ALBUM_IMAGE = 'UPDATE_ALBUM_IMAGE';
export const OPEN_ALBUM_SCREEN = 'OPEN_ALBUM_SCREEN';
export const VERY_FIRST_LAST_TRACK = 'VERY_FIRST_LAST_TRACK';

export const LOAD_AUDIO = 'LOAD_AUDIO';
export const UPDATE_TRACK_ID = 'UPDATE_TRACK_ID';
export const IS_TRACK_PLAYING = 'IS_TRACK_PLAYING';
export const IS_MINIMAZED = 'IS_MINIMAZED';
export const UPDATE_LOADED_SIZE = 'UPDATE_LOADED_SIZE';
export const TRACK_LOADING_ERROR = 'TRACK_LOADING_ERROR';
export const UPDATE_TIME = 'UPDATE_TIME';
export const HANDLE_PREV_NEXT = 'HANDLE_PREV_NEXT';
export const QUEUE_ENDED = 'QUEUE_ENDED';
export const UPDATE_PRESSED = 'UPDATE_PRESSED';
export const MOVE_TO_NEXT_ALBUM = 'MOVE_TO_NEXT_ALBUM';

export const ALL_SONGS_DATA = 'ALL_SONGS_DATA';
export const LAST_INPUTS = 'LAST_INPUTS';

export const IS_SETTINGS_VISIBLE = 'IS_SETTINGS_VISIBLE';
export const IS_ALBUM_LOADING = 'IS_ALBUM_LOADING';
