export const LOAD_ALBUMS = 'LOAD_ALBUMS';
export const TOGGLE_ALBUM = 'TOGGLE_ALBUM';

export const LOAD_PLAYER = 'LOAD_PLAYER';
export const LOAD_AUDIO = 'LOAD_AUDIO';
export const UPDATE_TRACK_ID = 'UPDATE_TRACK_ID';
export const INIT_PLAYER = 'INIT_PLAYER';
export const UPDATE_LOADED_SIZE = 'UPDATE_LOADED_SIZE';
export const TRACK_LOADING_ERROR = 'TRACK_LOADING_ERROR';
export const TRACK_PLAYER_CREATING = 'TRACK_PLAYER_CREATING';
export const UPDATE_STORAGE = 'UPDATE_STORAGE';
